import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { cn } from "@/lib/utils";
import Navbar from "@/components/navbar";

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Classmate",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClerkProvider
        appearance={{
          elements: {
            footer: "hidden",
          },
        }}
      >
        <body
          className={cn(
            "dark min-h-screen bg-background font-sans antialiased",
            fontSans.variable,
          )}
        >
          <Navbar />
          <div className="container py-6">{children}</div>
        </body>
      </ClerkProvider>
    </html>
  );
}
